// FREE operator script (SQL only — no Voyage, no LLM): convert the title-keyed v1 gold
// rows in test/fixtures/recall-eval.json to the STABLE-ID-keyed v2 shape by resolving
// each `relevantTitles` entry to its memory id in the live DB.
//
// This script only PROPOSES (GRAFT 2 / AC-109): it writes a NEW file —
// test/fixtures/recall-eval.v2.json — for HUMAN review and NEVER overwrites the v1
// file. No gold ID enters a split without human approval; the operator verifies every
// resolved id, assigns ~1/3 of rows to split "test" (G0 step 4), then renames the
// approved file over recall-eval.json and freezes the test split.
//
// Read-only by construction: the only SQL issued is a SELECT (unit-tested).
// Gate: `npm run gold:migrate`.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { Pool } from "pg";
import { pool as defaultPool } from "./pool.js";
import { config } from "../config.js";

const here = dirname(fileURLToPath(import.meta.url));
// src/db -> ../../test/fixtures (tsx) ; dist/db -> ../../test/fixtures (compiled)
const fixturesDir = join(here, "..", "..", "test", "fixtures");

export interface GoldRowV2 {
  id: string;
  query: string;
  relevantIds: string[];
  archetype?: string;
  split: "dev" | "test";
  provenance: "seed-v1" | "distilled" | "log-harvest";
  approvedBy?: string;
}

export interface GoldFileV2 {
  version: 2;
  k: number;
  changelog: string[];
  rows: GoldRowV2[];
}

interface V1Row {
  query: string;
  relevantTitles: string[];
}

interface V1File {
  k: number;
  rows: V1Row[];
}

export interface MigrateGoldDeps {
  pool: Pool;
  log?: (msg: string) => void;
}

export interface MigrateGoldResult {
  file: GoldFileV2;
  unresolvedTitles: string[];
  /** Normalized titles matching MORE than one memory id — the picked id is ambiguous
   *  and the human approver must verify it (AC-109). */
  duplicateTitles: { title: string; ids: string[] }[];
  outPath: string;
}

/**
 * Resolve every v1 `relevantTitles` entry to a memory id by exact (trimmed,
 * case-insensitive) title match in the live DB and emit the v2 gold file for human
 * review. Unresolved titles are reported (the operator fixes them by hand); rows keep
 * whatever ids DID resolve so the review file is complete.
 */
export async function migrateGold(
  deps: MigrateGoldDeps,
  opts: {
    projectId: string;
    evalPath?: string;
    outPath?: string;
  },
): Promise<MigrateGoldResult> {
  const log = deps.log ?? ((m: string) => console.error(m));
  const evalPath = opts.evalPath ?? join(fixturesDir, "recall-eval.json");
  const outPath = opts.outPath ?? join(fixturesDir, "recall-eval.v2.json");

  const v1 = JSON.parse(readFileSync(evalPath, "utf8")) as V1File;
  if (!Array.isArray(v1.rows) || typeof v1.k !== "number") {
    throw new Error("v1 eval file must have { k: number, rows: [...] }");
  }

  // One read-only SELECT for ALL titles: normalized-title -> id.
  const allTitles = [
    ...new Set(
      v1.rows.flatMap((r) =>
        r.relevantTitles.map((t) => t.trim().toLowerCase()),
      ),
    ),
  ];
  const { rows: dbRows } = await deps.pool.query<{ id: string; title: string }>(
    `SELECT id, title FROM memory.memories
     WHERE project_id = $1 AND lower(trim(title)) = ANY($2)`,
    [opts.projectId, allTitles],
  );
  // First id wins, but COLLISIONS (one normalized title -> several ids) are collected
  // and surfaced: the resolution is ambiguous and must be visible to the human approver.
  const idByTitle = new Map<string, string>();
  const idsByTitle = new Map<string, string[]>();
  for (const r of dbRows) {
    const key = r.title.trim().toLowerCase();
    if (!idByTitle.has(key)) idByTitle.set(key, r.id);
    const ids = idsByTitle.get(key);
    if (ids) ids.push(r.id);
    else idsByTitle.set(key, [r.id]);
  }
  const duplicateTitles = [...idsByTitle.entries()]
    .filter(([, ids]) => ids.length > 1)
    .map(([title, ids]) => ({ title, ids }));

  const unresolved = new Set<string>();
  const rows: GoldRowV2[] = v1.rows.map((r, i) => {
    const relevantIds: string[] = [];
    for (const t of r.relevantTitles) {
      const id = idByTitle.get(t.trim().toLowerCase());
      if (id) relevantIds.push(id);
      else unresolved.add(t);
    }
    return {
      id: `m-${String(i + 1).padStart(3, "0")}`,
      query: r.query,
      relevantIds,
      // Default split for ALL seeds is "dev"; the operator promotes ~1/3 to "test"
      // before freezing (G0 step 4). This script never assigns "test" itself.
      split: "dev",
      provenance: "seed-v1",
    };
  });

  const file: GoldFileV2 = {
    version: 2,
    k: v1.k,
    changelog: [
      `${new Date().toISOString().slice(0, 10)}: v2 PROPOSAL generated by gold:migrate ` +
        `(title -> stable id, all rows split:"dev"). PENDING HUMAN APPROVAL — no gold id ` +
        `enters a split without it (AC-109); the test split is modified only by flip gates.`,
      // Ambiguous resolutions go INTO the review file so the approver cannot miss them.
      ...duplicateTitles.map(
        (d) =>
          `AMBIGUOUS title "${d.title}" matched ${d.ids.length} memories ` +
          `[${d.ids.join(", ")}] — first id used; VERIFY before approval.`,
      ),
    ],
    rows,
  };

  writeFileSync(outPath, JSON.stringify(file, null, 2) + "\n");

  const unresolvedTitles = [...unresolved];
  if (unresolvedTitles.length > 0) {
    log(`gold:migrate — ${unresolvedTitles.length} UNRESOLVED title(s):`);
    for (const t of unresolvedTitles) log(`  - ${t}`);
    log("Fix these by hand in the v2 file (look the ids up yourself).");
  }
  if (duplicateTitles.length > 0) {
    log(
      `gold:migrate — ${duplicateTitles.length} AMBIGUOUS title(s) (several memories share the title; first id used):`,
    );
    for (const d of duplicateTitles)
      log(`  - ${d.title} -> ${d.ids.join(", ")}`);
    log("Verify each picked id in the v2 file before approval (AC-109).");
  }
  log(
    `gold:migrate — wrote ${outPath}` +
      ` (${rows.length} rows, all split:"dev").`,
  );
  log(
    'REMINDER: review every resolved id, assign ~1/3 of rows to split:"test", set ' +
      "approvedBy, then rename the file over recall-eval.json (the v1 file was NOT touched).",
  );

  return { file, unresolvedTitles, duplicateTitles, outPath };
}

// ── CLI entrypoint (npm run gold:migrate) ────────────────────────────────────────────
// Skipped when imported (tests import migrateGold directly).
const isMain = process.argv[1]
  ? import.meta.url === new URL(`file://${process.argv[1]}`).href
  : false;

if (isMain) {
  (async () => {
    await migrateGold(
      { pool: defaultPool },
      { projectId: config.defaultProjectId },
    );
    await defaultPool.end();
  })().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
